### PR TITLE
Map consolidation

### PR DESCRIPTION
**Pull request by richardbeare**
Think I have the analytics sorted out now.

### CODE REVIEW

**Comment by GNtem2** [comment]
The tibble command has not quite changed UK to Great Britain and USA to United States

Initially, I hd used: TableS1$Countries <- str_replace(TableS1$Countries,"USA","United States") %>%
    str_replace("Great Britain","United Kingdom")

**Comment by GNtem2** [comment]
@richardbeare 
The tibble command has not quite changed UK to Great Britain and USA to United States
Initially, I hd used: TableS1$Countries <- str_replace(TableS1$Countries,"USA","United States") %>%
str_replace("Great Britain","United Kingdom")

**Comment by richardbeare** [comment]
I attempted to do it with a join, which I thought was neater. Will check if I missed something.

Still working on the analytics. Nearly there.

**Comment by GNtem2** [comment]
I think tibble did not quite do it but more elegant in terms of less coding

str_replace is  much better

this is the vic crime data

https://www.crimestatistics.vic.gov.au/explore-crime-by-location

Thanh

Professor Thanh G Phan
FRACP, PhD
Hudson Institute Building,
27 Wright Street, Clayton
Level 3, Room L3.66
Office Number +61385722612
Github page: https://github.com/GNtem2
CTI Web page:
https://www.monash.edu/medicine/scs/research/star/clin-trials-imaging-informatics
Geospatial Analysis:*https://www.monash.edu/medicine/scs/medicine/research/geospatial-analysis
<https://www.monash.edu/medicine/scs/medicine/research/geospatial-analysis>*

**Pull request merged**
